Run docker prune automatically when needed during deployment

diff --git a/lib/generators/terra_boi/templates/lib/scripts/push_to_ecr.sh.erb b/lib/generators/terra_boi/templates/lib/scripts/push_to_ecr.sh.erb
--- a/lib/generators/terra_boi/templates/lib/scripts/push_to_ecr.sh.erb
+++ b/lib/generators/terra_boi/templates/lib/scripts/push_to_ecr.sh.erb
@@ -12,7 +12,11 @@ aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --
 
 # Build your Docker image using the following command
 DOCKERFILE_PATH="$SCRIPT_DIR/../../../."
-docker build -t $AWS_ECR_REPO_NAME $DOCKERFILE_PATH
+if ! docker build -t $AWS_ECR_REPO_NAME $DOCKERFILE_PATH; then 
+	echo "TERRA_BOI | Command failed. Pruning Docker memory then retrying!"
+	echo "TERRA_BOI | Pruning may take a couple minutes..."
+	docker system prune -a && docker build -t $AWS_ECR_REPO_NAME $DOCKERFILE_PATH
+fi
 
 # After the build completes, tag your image so you can push the image to this repository:
 docker tag $AWS_ECR_REPO_NAME:latest $AWS_ECR_REPO_URL:latest
